[tools]
go = "1.24.2"

[env]
_.file = ".env"

[tasks.fmt]
description = "Format Go code"
run = "gofmt -w ./cmd ./internal"

[tasks.test]
description = "Run Go tests"
run = "go test ./..."

[tasks.build]
description = "Build the CLI"
run = "go build -o ./bin/summond ./cmd/summond"

[tasks.install-bin]
description = "Build the CLI and copy it into ~/.bin and Application Support dirs"
depends = ["build"]
run = """
mkdir -p ~/.bin && cp bin/summond ~/.bin
cp bin/summond "$HOME/Library/Application Support/summond/bin/summond"
sudo install -m 0755 bin/summond "/Library/Application Support/summond/bin/summond"
"""
